version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq_todo
    restart: always
    ports:
      - 5672:5672
      - 8080:15672
    env_file:
      - .env
    networks:
      - todoservice
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
  mongodb:
    image: mongo:latest
    container_name: mdb_todo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mdb_data:/data/db
networks:
  todoservice:
    driver: bridge
volumes:
  mdb_data:
